# config.yaml (VERSÃO SIMPLIFICADA E CORRETA)

# Provedor de LLM a ser usado. Atualmente suporta: "openrouter"
llm_provider: "openrouter"

# Mapeia os papéis dos agentes para modelos de IA específicos.
# Nós atualizamos nosso código para esperar um modelo para o Executor também.
model_mapping:
  planner: "anthropic/claude-3-haiku"
  executor: "anthropic/claude-3-haiku"

# Chave de API para o OpenRouter.
# Esta chave será lida da variável de ambiente OPENROUTER_API_KEY se não for especificada aqui.
# É uma boa prática de segurança usar variáveis de ambiente em vez de colocar a chave diretamente aqui.
# openrouter_api_key: "sk-or-..." 

