# config.yaml
api_settings:
  default_provider: "openrouter"
  provider:
    openrouter:
      base_url: "https://openrouter.ai/api/v1"
      # Esta linha precisa conter o NOME da variável, não o valor dela.
      api_key_env: "OPENROUTER_API_KEY"

model_mapping:
  planner: "anthropic/claude-3-haiku-20240307"
  executor: "anthropic/claude-3-haiku-20240307"
  validator: "anthropic/claude-3-haiku-20240307"

engine_settings:
  max_iterations: 25
  security_level: "strict"
